### ISSUE TITLE
Cannot get URI type if using `/favorites/create/{id}` API

### ISSUE THREAD

**Issue by tat757** [fanfoujs/fanfou-sdk-node#37]
当使用<code>/favorite/create</code>时会报错
![8](https://user-images.githubusercontent.com/7260758/58020803-d480ab80-7b3b-11e9-8f44-89ab73921864.png)

查了下源码，发现当使用这个<code>/favorite/create</code>时，<code>got.post</code>返回的body(源码index.js的120行)是个空的array。这就导致后边的<code>new Status</code>时<code>this._getSourceUrl()</code>不能match。

![6](https://user-images.githubusercontent.com/7260758/58020721-984d4b00-7b3b-11e9-9d47-53cb30559dc0.png)

同时测试了<code>/statuses/destroy</code>返回的body里有内容
![7](https://user-images.githubusercontent.com/7260758/58021023-6dafc200-7b3c-11e9-9704-4bb1960e0447.png)

**Comment by tat757** [comment]
刚看了下网页版。发现网页版的收藏链接已经改成了"/favorite.add/:id“了。是收藏的API已经改了吗？

**Comment by tat757** [comment]
收藏和删除在API里的上传接口好像不一样
收藏的接口：
<code>http://api.fanfou.com/favorites/create/:id.[json|xml|rss]</code>
删除的接口：
<code>http://api.fanfou.com/statuses/destroy.[json|xml|rss]</code>
用post的时候应该会有些区别的吧。

**Comment by LitoMore** [comment]
@tat757 請注意看飯否的官方文檔，路徑是 `http://api.fanfou.com/favorites/create/:id.[json|xml|rss]`

即 `http://api.fanfou.com/favorites/create/your_id.json`

這裡 fanfou-sdk 應該沒有 bug

請參考 https://github.com/LitoMore/fandark/blob/master/unfav.js#L26

**Comment by tat757** [comment]
我看文档下边写的 id是消息id 我还以为说的是链接上的这个id。

https://github.com/LitoMore/fanfou-sdk-node/blob/master/src/index.js#L101

请问下，上边这段代码使用<code>/favorite/create</code>时这里的<code>uri</code>是应该用<code>/favorite/create/{{userId}}</code>吗？
如果这样的话，下边的<code>_uriType(uri)</code>函数里的和<code>favorite</code>有关的链接是不是就都返回<code>null</code>了？

**Comment by tat757** [comment]
感谢，改成```/favorite/create/{{userId}}```就可以正常使用了。

**Comment by LitoMore** [comment]
> 如果这样的话，下边的_uriType(uri)函数里的和favorite有关的链接是不是就都返回null了？

嗯，你說得對，這裏的確是有 bug，我下個版本修正一下。

**Comment by LitoMore** [comment]
@tat757 在 `fanfou-sdk@4.0.5` 中修復了。
