### ISSUE TITLE
GET `/favorites/{id}`  does not return 'txt'

### ISSUE THREAD

**Issue by tat757** [fanfoujs/fanfou-sdk-node#38]
原因可能和create/destroy一样。```_uriType()```不能正确的把```/favorites/{id}``` 识别成```status```。这会导致最终结果没有返回txt。

**Comment by LitoMore** [comment]
這個接口沒有問題，id 不應該放在 URL 裡傳，這個接口和 statuses/show 的接口的用法是一樣的。

**Comment by tat757** [comment]
好吧。。 我看文档```/favorites```也有个```id```，我以为要和```favorites/create```一样。
