### ISSUE TITLE
xauth error in React

### ISSUE THREAD

**Issue by elegracer** [fanfoujs/fanfou-sdk-node#41]
I was trying developing a fanfou client based on React framework on my mac.

I created a minimal React project using `npx create-react-app` from `node` installed with `brew install node`.

I just modified `App.js` to the following code with the option items assigned correctly, and ran `npm start`.

```js
import React from 'react';
import logo from './logo.svg';
import './App.css';
const Fanfou = require('fanfou-sdk');

function App() {
    const ff = new Fanfou({
        consumerKey: 'SOME_CONSUMER_KEY',
        consumerSecret: 'SOME_CONSUMER_SECRET',
        username: 'MY_EMAIL',
        password: 'MY_PASSWORD'
    });

    ff.xauth().then(res => console.log(res)).catch(err => console.log(err));

    return (
        <div className="App">
            <header className="App-header">
                <img src={logo} className="App-logo" alt="logo" />
                <p>
                    Edit <code>src/App.js</code> and save to reload.
        </p>
                <a
                    className="App-link"
                    href="https://reactjs.org"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Learn React
        </a>
            </header>
        </div>
    );
}

export default App;

```

But in the console, it showed the following error message.

```
FanfouError: Right-hand side of 'instanceof' is not an object
    at Fanfou.xauth (http://localhost:3000/static/js/0.chunk.js:6355:13)
```

However, if I run a single `test.js` file with the following code directly using `node test.js`, the response is successfully received and printed in the console.

```js
const Fanfou = require('fanfou-sdk');

const ff = new Fanfou({
    consumerKey: 'SOME_CONSUMER_KEY',
    consumerSecret: 'SOME_CONSUMER_SECRET',
    username: 'MY_EMAIL',
    password: 'MY_PASSWORD'
});

ff.xauth().then((res) => console.log(res)).catch((err) => console.log(err));
```

Unable to contact to you directly so I open this issue. Many thanks if you could give me a hand with this.

**Comment by LitoMore** [comment]
@elegracer For web app, you should use [fanfou-sdk-browser](https://github.com/LitoMore/fanfou-sdk-browser) instead.

**Comment by elegracer** [comment]
ummmm...so may I reckon that this error originates from the differences between the pure node and the React framework?

**Comment by LitoMore** [comment]
This error is form here: https://github.com/sindresorhus/got/issues/693.

**Comment by elegracer** [comment]
Oh..So it's got...Thank you for you help! I will try fanfou-sdk-browser later.
